// Generated by scripts/sync-deployment.mjs. Do not edit.
export { default as launchRecord } from "./1.json" with { type: "json" };
export { default as launchpadRecord } from "./1.launchpad.json" with { type: "json" };
export { default as launchpadV2Record } from "./1.launchpad-v2.json" with { type: "json" };
