// Generates the typed ABIs (src/chain/abi.ts) and the creation-code templates the launchpad needs
// (src/chain/bytecode.ts) from the Foundry artifacts in ../contracts/out. Run after `forge build`:
//   node scripts/gen-abi.mjs          write both modules
//   node scripts/gen-abi.mjs --check  fail when a module is stale
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "..", "contracts", "out");
const HEADER = "// GENERATED by scripts/gen-abi.mjs from contracts/out — do not edit.\n";
const CONTRACTS = [
  "CubitToken", "CubitHook", "CubitLens", "CubitRouter", "CubitV2",
  "CubitVault", "CubitLaunch", "CubitForge", "CubitGovernanceVault",
  // Launchpad v2: children paired with a quote currency (ETH, USDC, USDT, WBTC, tokenized stocks).
  "CubitForgeV2", "CubitQuoteHook",
  // Launchpad v3: ERC-20 pairs in the TOKEN/QUOTE orientation.
  "CubitForgeV3", "CubitTokenFirstHook",
];

const artifact = (file, name) => JSON.parse(readFileSync(join(out, `${file}.sol`, `${name}.json`), "utf8"));

let abi = HEADER;
for (const name of CONTRACTS) abi += `\nexport const ${name}Abi = ${JSON.stringify(artifact(name, name).abi)} as const;\n`;
abi += `\nexport const CubitForgeTokenAbi = ${JSON.stringify(artifact("CubitForge", "CubitForgeToken").abi)} as const;\n`;

const hook = artifact("CubitHook", "CubitHook").bytecode;
const childToken = artifact("CubitForge", "CubitForgeToken").bytecode;
const links = {};
for (const libraries of Object.values(hook.linkReferences ?? {})) {
  for (const [library, positions] of Object.entries(libraries)) links[library] = positions;
}
if (Object.keys(childToken.linkReferences ?? {}).length) throw new Error("CubitForgeToken is not expected to link a library");

const quoteHook = artifact("CubitQuoteHook", "CubitQuoteHook").bytecode;
const quoteLinks = {};
for (const libraries of Object.values(quoteHook.linkReferences ?? {})) {
  for (const [library, positions] of Object.entries(libraries)) quoteLinks[library] = positions;
}

const tokenFirstHook = artifact("CubitTokenFirstHook", "CubitTokenFirstHook").bytecode;
const tokenFirstLinks = {};
for (const libraries of Object.values(tokenFirstHook.linkReferences ?? {})) {
  for (const [library, positions] of Object.entries(libraries)) tokenFirstLinks[library] = positions;
}

const bytecode = HEADER +
  "// The CubitHook creation code keeps its library placeholders: the launchpad links BandLib and WallLib at the addresses\n" +
  "// of the live deployment, then checks the result against CubitForge.hookCreationCodeHash() before any launch.\n" +
  `export const HOOK_CREATION_CODE = "${hook.object}" as const;\n` +
  `export const HOOK_LINK_REFERENCES = ${JSON.stringify(links)} as const;\n` +
  "// A child token's CREATE2 init code is this creation code followed by abi.encode(name, symbol).\n" +
  `export const FORGE_TOKEN_CREATION_CODE = "${childToken.object}" as const;\n` +
  "// Launchpad v2: the CubitQuoteHook creation code, linked to BandLib and QuoteWallLib by the app, then checked\n" +
  "// against CubitForgeV2.hookCreationCodeHash() before any launch.\n" +
  `export const QUOTE_HOOK_CREATION_CODE = "${quoteHook.object}" as const;\n` +
  `export const QUOTE_HOOK_LINK_REFERENCES = ${JSON.stringify(quoteLinks)} as const;\n` +
  "// Launchpad v3: the CubitTokenFirstHook creation code (an ERC-20 pair's hook), linked to BandLib and TokenFirstWallLib by\n" +
  "// the app, then checked against CubitForgeV3.tokenFirstHookCreationCodeHash() before any launch.\n" +
  `export const TOKEN_FIRST_HOOK_CREATION_CODE = "${tokenFirstHook.object}" as const;\n` +
  `export const TOKEN_FIRST_HOOK_LINK_REFERENCES = ${JSON.stringify(tokenFirstLinks)} as const;\n`;

const targets = [[join(root, "src", "chain", "abi.ts"), abi], [join(root, "src", "chain", "bytecode.ts"), bytecode]];
if (process.argv.includes("--check")) {
  for (const [path, content] of targets) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) throw new Error(`Stale ${path}: run node scripts/gen-abi.mjs`);
  }
  console.log("ABI and bytecode modules are current");
} else {
  mkdirSync(join(root, "src", "chain"), { recursive: true });
  for (const [path, content] of targets) writeFileSync(path, content);
  console.log(`wrote src/chain/abi.ts (${CONTRACTS.length + 1} contracts) and src/chain/bytecode.ts (links: ${Object.keys(links).join(", ")}; v2: ${Object.keys(quoteLinks).join(", ")})`);
}
